export const Categories=[
{id: 0,type:'All'},
{id: 1,type:'Fashion'},
{id: 2,type:'Beauty'},
{id: 3,type:'Travel'},
{id: 4,type:'Lifestyle'},
{id: 5,type:'Personal'},
{id: 6,type:'Tech'},
{id: 7,type:'Health'},
{id: 8,type:'Fitness'},
{id: 9,type:'Wellness'},
{id: 10,type:'SaaS'},
{id: 11,type:'Business'},
{id: 12,type:'Education'},
{id: 13,type:'Food and Recipe '},
{id: 14,type:'Love and Relationships'},
{id: 15,type:'Alternative topics'},
{id: 16,type:'Green living'},
{id: 17,type:'Music'},
{id: 18,type:'Automotive'},
{id: 19,type:'Marketing'},
{id: 20,type:'Internet services'},
{id: 21,type:'Finance'},
{id: 22,type:'Sports'},
{id: 23,type:'Entertainment'},
{id: 24,type:'Productivity'},
{id: 25,type:'Hobbies'},
{id: 26,type:'Parenting'},
{id: 27,type:'Pets'},
{id: 28,type:'Photogaphy'}
]